project:
  output-dir: docs
  type: website
  resources:
    - figures/**

website:
  title: "refloraR"
  site-url: https://dboslab.github.io/refloraR-website/
  page-navigation: true
  reader-mode: true  
  favicon: "figures/refloraR_hex_sticker.png"
  
  page-footer:
    center:
      - text: "About"
        href: about.qmd
      - text: "FAQ"
        href: faq/index.qmd
      - text: "License"
        href: LICENSE.md
    right:
      - icon: github
        href: https://github.com/DBOSlab/refloraR
        aria-label: refloraR GitHub
  
  navbar:
    search: true
    background: light
    collapse-below: lg
    type: light
    logo: "figures/refloraR_hex_sticker.png"
    href: index.qmd
    left:
      - text: "Overview"
        href: index.qmd
      - text: "Get Started"
        href: get-started/index.qmd
      - text: "Articles"
        href: articles/index.qmd
      - text: "News"
        href: packages/refloraR/latest/news.md 
      - text: "Reference"
        href: reference.qmd
      - text: "Help"
        menu:
          - text: "Report a Bug"
            icon: "bug"
            href: "https://github.com/DBOSlab/refloraR/issues"
          - text: "Ask a Question"
            icon: "chat-right-text"
            href: "https://github.com/DBOSlab/refloraR/discussions"
          - text: "FAQ"
            icon: "question-circle"
            href: faq/index.qmd
        
    tools:
      - icon: github
        href: https://github.com/DBOSlab/refloraR
        text: refloraR GitHub
        
  sidebar:
    - id: get-started
      title: Get Started
      collapse-level: 2
      style: "floating"
      align: left
      contents:
        - href: get-started/index.qmd
                
    - id: articles
      title: Articles
      collapse-level: 3
      align: left
      contents:
        - text: Overview
          href: articles/index.qmd
        - section: Summarize REFLORA collections
          contents:
          - text: Summarize herbarium collections 
            href: articles/summarize_reflora_collections.qmd  
        - section: Download REFLORA specimen records
          contents:
          - text: Download specimen records 
            href: articles/download_reflora_collections.qmd
        - section: Filter REFLORA specimen records
          contents:
          - text: Filter specimen records 
            href: articles/filter_reflora_records.qmd

format:
  html:
    toc: true
    embed-resources: true
    code-copy: true
    code-overflow: wrap
    code-tools: true
    css: styles.css
    eval: false
    theme:
      light: [spacelab, theme.scss]
      dark: [spacelab, theme-dark.scss]
    include-in-header: gtm-head.html
    include-before-body: gtm-body.html
