---
title: 'reflora_summary'
description: 'Summarize current plant specimen records at REFLORA Virtual Herbarium'
toc: true
toc-depth: 3
---


```{r}
#| eval: false
refloraR::reflora_summary()
```

### Description

Summarize current available plant specimen records at
[REFLORA Virtual Herbarium](https://ipt.jbrj.gov.br/reflora/)
hosted by the [Rio de Janeiro Botanical Garden](https://www.gov.br/jbrj/pt-br).
REFLORA aggregates collections from both Brazilian and international herbaria
that hold Brazilian specimens. In this context, “digital repatriation” refers
to making high-resolution images and associated specimen metadata openly
accessible through a Brazilian public infrastructure (HVR/IPT), even when the
physical specimens remain curated in the holding herbarium. The
`reflora_summary()` output includes a repatriation status field to help
users identify these digitally repatriated collections.

### Arguments

| Argument | Description |
|---|---|
| herbarium | A vector of specific herbarium acronyms (collection code) in uppercase letters or leave it as `NULL` to summarize specimen records for all REFLORA-hosted herbaria. |
| verbose | Logical, if `FALSE`, a message showing steps when summarizing specimen records will not be printed in the console in full. |
| save | Logical, if `TRUE`, the search results will be saved on disk. |
| dir | Pathway to the computer's directory, where the table-formatted summary will be saved. The default is to create a directory named `reflora_summary`. |

### Value

A `data.frame` with one row per herbarium collection and the
following columns:

collectionCodeCharacter. Herbarium acronym (collection code) as
registered in the REFLORA Virtual Herbarium.

rightsHolderCharacter. Institution responsible for the collection,
as reported in the IPT metadata.

RepatriatedLogical. Indicates whether the herbarium corresponds to
a repatriated collection (i.e., Brazilian specimens digitized from foreign
institutions such as US, NY, K, etc.).

contactPointCharacter. Name of the contact person or curator
associated with the collection.

hasEmailCharacter. Contact email address for the contactPoint,
when available.

VersionCharacter. Current dataset version number available in
the IPT repository.

Published.onCharacter. Date and hour on which the current dataset
version was published in the IPT.

RecordsNumeric. Total number of specimen records currently
available for the collection.

Reflora_URLCharacter. Direct URL to the collection page in the
REFLORA Virtual Herbarium.

### Examples

```r
reflora_summary(herbarium = c("ALCB", "HUEFS"),
                verbose = TRUE,
                save = TRUE,
                dir = "reflora_summary")
```


